export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_FANTASY = 'FETCH_FANTASY';
export const SET_NAVBAR_ACTIVE_ITEM = 'SET_NAVBAR_ACTIVE_ITEM';
